name: Build Linux

on:
    push:
        # branches: [ "main" ]
    pull_request:
        branches: ["main"]

jobs:
    build-deb:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v4
              with:
                submodules: true

            - name: Prepare dependencies
              run: |
                  sudo apt update
                  sudo apt install cmake libboost-thread-dev libasio-dev qt6-base-dev libqt6websockets6-dev libqt6gui6 libqt6widgets6 libqt6core5compat6-dev libgl1-mesa-dev libvlc-dev libvlccore-dev
              env:
                  CI: 1

            - name: Run build
              run: |
                  ./tools/build-linux.sh
              env:
                  CI: 1

            - name: Upload build
              id: "upload-build"
              shell: bash
              run: |
                  TARGET=casparcg-client-${{ github.sha }}-ubuntu22.deb
                  mv build/CasparCG*.deb "$TARGET"

                  echo "artifactname=$TARGET" >> $GITHUB_OUTPUT

                  # check if a release branch, or main, or a tag
                  if [[ "${{ github.ref_name }}" == "main" || "${{ github.ref_name }}" == "2.3.x-lts" ]]
                  then
                    # Only proceed if we have an sftp password
                    if [ -n "${{ secrets.SFTP_PASSWORD }}" ]
                    then

                        echo "uploadname=$TARGET" >> $GITHUB_OUTPUT

                        set -x
                        eval $(ssh-agent -s)
                        mkdir -v -m 700 $HOME/.ssh
                        ssh-keyscan -H ${{ secrets.SFTP_HOST }} > $HOME/.ssh/known_hosts
                        sshpass -p '${{ secrets.SFTP_PASSWORD }}' rsync -avvz --mkpath "${TARGET}" "${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:${{ secrets.SFTP_ROOT }}/${{ github.ref_name }}/${TARGET}"
                    fi
                  fi

            - uses: actions/upload-artifact@v4
              with:
                  name: upload-artifact
                  path: ${{ steps.upload-build.outputs.artifactname }}
